version: '3.9'

# networks:
#   wordpress:

services:
  nginx:
    build:
      context: .
      dockerfile: nginx.dockerfile
    # container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./wordpress:/var/www/html:delegated
    depends_on:
      - php
      - mysql
    # networks:
    #   - wordpress

  mysql:
    image: mysql:latest
    # container_name: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: wp
      MYSQL_USER: wp
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    volumes: 
      - ./mysql:/var/lib/mysql

      # SERVICE_TAGS: dev
      # SERVICE_NAME: mysql
    # networks:
    #   - wordpress

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    depends_on:
      - mysql
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1


   
  php:
    build:
      context: .
      dockerfile: php.dockerfile
    # container_name: php
    volumes:
      - ./wordpress:/var/www/html:delegated
    # networks:
    #   - wordpress

  wp:
    build:
      context: .
      dockerfile: php.dockerfile
  #   container_name: wp
    entrypoint: ['wp', '--allow-root']
    volumes:
      - ./wordpress:/var/www/html:delegated
  #   networks:
  #     - wordpress